arb-dir: lib/l10n
output-dir: lib/src/generated/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
arb-translate-api-key: AIzaSyB2Zl..........j4ndVHNwk-YPOnbCVQQ
arb-translate-model: gemini-1.5-flash