// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOA7n91OBB4Y_OFIW3yDAxuCJVuHHRDnk',
    appId: '1:973717899498:web:173e36a64c84df2d80ef93',
    messagingSenderId: '973717899498',
    projectId: 'lifeflow-nvh',
    authDomain: 'lifeflow-nvh.firebaseapp.com',
    storageBucket: 'lifeflow-nvh.firebasestorage.app',
    measurementId: 'G-7P76ZX0STE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnvTkHvnBIaNuW99UlldgJ7UeLylg94Hs',
    appId: '1:973717899498:android:7204a5dd76ee9e4380ef93',
    messagingSenderId: '973717899498',
    projectId: 'lifeflow-nvh',
    storageBucket: 'lifeflow-nvh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX6kZast7i2hJJMdKyBPBJP23WNXnTzQ0',
    appId: '1:973717899498:ios:6acdbe3996c53a6c80ef93',
    messagingSenderId: '973717899498',
    projectId: 'lifeflow-nvh',
    storageBucket: 'lifeflow-nvh.firebasestorage.app',
    iosBundleId: 'com.nvh.lifeflow',
  );

}