// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbAUSvoVLCIm_JkMewXPVRH86f1H6Zr0I',
    appId: '1:698817676474:web:293a0234b5315d979bae83',
    messagingSenderId: '698817676474',
    projectId: 'lifeflow-azvn',
    authDomain: 'lifeflow-azvn.firebaseapp.com',
    storageBucket: 'lifeflow-azvn.firebasestorage.app',
    measurementId: 'G-102SSX4VZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX3G0vVOcB5-_fiH1hVLy1P8tkHUtF4XE',
    appId: '1:698817676474:android:4453d5e6c6cdf0919bae83',
    messagingSenderId: '698817676474',
    projectId: 'lifeflow-azvn',
    storageBucket: 'lifeflow-azvn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1VDFSYUu6NsZ3HO7ZgAVDGzJLbSGfyf4',
    appId: '1:698817676474:ios:95befe77da79c5409bae83',
    messagingSenderId: '698817676474',
    projectId: 'lifeflow-azvn',
    storageBucket: 'lifeflow-azvn.firebasestorage.app',
    iosBundleId: 'com.azeravn.lifeflow',
  );
}
